import { AppShell } from "@/components/layout/AppShell/AppShell";
import { COMPANY_NAME } from "@/constants/company";
import type { ReactComponent } from "@/types";
import { cn } from "@/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: {
    template: `%s | ${COMPANY_NAME}`,
    default: COMPANY_NAME,
  },
  description: "Generated by create next app",
};

const RootLayout: ReactComponent = ({ children }) => {
  return (
    <html lang="en" className={cn("h-full bg-white", inter.variable)}>
      <body className="h-full">
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
};

export default RootLayout;
